[workspace]
authors = ["Arushi Sinha <115908316+arushisinha98@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "Document-parser"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
pillow = ">=12.1.1,<13"
opencv = ">=4.13.0,<5"
