[workspace]
authors = ["Kirsty Kirkman <kirsty.kirman@outlook.com>"]
channels = ["conda-forge"]
name = "Document-parser"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
pillow = ">=12.1.1,<13"
opencv = ">=4.13.0,<5"
numpy = ">=2.4.2,<3"
